### ISSUE TITLE
Change in top donors page 

### ISSUE THREAD

**Issue by abdulriza** [undp/undp.github.com#154] opened 2015-08-06 16:30 UTC
@Jura As discussed, we need to change the way we present the top donor by combining the existing two tables into one. Currently we show top 20 contributing non-programme country donors in the top table and top 10 programme country donors in a separate  table. Partnership group has suggested that the top contributors needs to be presented in one table despite whether it is porgamme or non-programme country. Two suggestions for the change;

1. We remove the second table and increase the number in the top table to 30 countries. This will have the same presentation of top 30 in a single table with different tabs for Regular, Other and Total numbers. 
2. We present three separate tables for Regular, Other and Total for 30 top countries. 

Let's discuss the options.

**Comment by Jura** [comment] 2015-08-10 19:54
Summary of discussion: @abdulriza will update donor_gross.csv file with the countries previously included into donor_local.csv and @jura will make sure that table shows 30 countries instead of 20 in only one table

**Comment by Jura** [comment] 2015-08-31 21:32
UPDATE from @abdulriza 

Hi Jura,

Please use the attached new table to update the top donors page on open.undp.org – Had to change India’s numbers. 

Also following is the footnotes we need to add and bring in the * next to India and Canada and ** to Australia in the table;

* Canada and India's contributions to 2014 regular resources were received in 2015.                                       
** Excludes Australia's contribution of USD18,154,657 to regular resources received in 2014 as it was intended for 2013.                                          
 
Let’s have the description as follows;

List of top donors is based on total income received for regular and other resources in 2014 (as of December 31, 2014) -Excludes Reimbursable Services and Miscellaneous Activities, and Government Local Office Costs (GLOC).

Best,
Riza

**Comment by Jura** [comment] 2015-08-31 21:33
@abdulriza - I've updated the code and committed to hotfix/issue-154 branch in my fork ( https://github.com/Jura/undp.github.com/tree/hotfix/issue-154). Kindly test and let me know if I can merge it to master

**Comment by Jura** [comment] 2015-09-01 14:34
Deployed

**Closed by Jura** 2015-09-01 14:34 UTC
